### ISSUE TITLE
SGF Library shows "?" outcome for some games

### ISSUE THREAD

**Issue by JDNdeveloper** [online-go/online-go.com#1348]
Related to https://github.com/online-go/goban/issues/26

On the SGF library page "?" is shown for games where the result couldn't be parsed due to the `RE` property being in an unexpected (but still SGF spec compliant) location.

![image](https://user-images.githubusercontent.com/4645409/103800767-a6e2c180-5001-11eb-9e80-09b6f062ad75.png)

This is distinct from the above issue as I'm introducing a client-side change to parse out the result if it's missing from the `outcome` in the game payload, however this isn't possible to do in the SGF library page so this still requires a server side fix to solve.

@anoek Does the server backend use the `GoEngine.ts` `parseSGF()` function to generate the game data? If so, will my fix there where I update `self.outcome` to the proper result solve this for newly uploaded SGFs? If so, this issue can be closed out once that fix is live, even though it will still be an issue for previously uploaded SGFs.

**Comment by anoek** [comment]
Yep it uses that code, so should work as you expect.

**Comment by JDNdeveloper** [comment]
@anoek Just to confirm, this will require server side changes and won't automatically be fixed by https://github.com/online-go/goban/pull/28 right?

**Comment by anoek** [comment]
Yeah unfortunately so, it turns out we're still using some old python code to get that out, and it doesn't seem to handle comments correctly in that block. I'll change it over to doing a request to get this information from a node.js server so we can use the same code (this code that you've fixed), but that's going to take a little re-wiring on my end before that works.

**Comment by shinuito** [comment]
There's still an issue when the result of a game is incomplete.

Eg if one takes a game like below from Waltheri, the result is recorded as "W+" which is throwing an error when trying to be uppercased for some reason.

http://ps.waltheri.net/database/game/13648/

At the moment the upload won't display any moves at all, so I would certainly prefer a [?] in the result display instead of not being able to view the game at all.
