### ISSUE TITLE
'Forgot your password' should email link rather than (newly generated) password

### ISSUE THREAD

**Issue by hickford** [online-go/online-go.com#176]
Right now 'forgot your password' at https://online-go.com/sign-in changes your password to a random number and emails it to you

> Someone (hopefully you!) has requested a password reset for your online-go.com
account. To proceed, simply login with the following credentials:
> Username: Guybrush Threepwood   
> Password: 123456

It would be better (more secure) to email a link instead https://www.gov.uk/service-manual/design/passwords#helping-users-who-forget-their-password

> You should never send passwords by email because it’s not a secure channel.
> 
> Instead, send users a time-limited password-reset link or code to the email address or phone number that they registered with.

**Comment by juanchodepisa** [comment]
Uhmmm, I'd have to agree with this.

There's a loophole where someone could claim to have forgotten a password for an account that's not theirs.
This would mean the original password would stop working, disrupting that player's usability of the server.

**Comment by anoek** [comment]
Agreed

**Comment by BHydden** [comment]
resolved.

**Comment by anoek** [comment]
This issue has been marked stale and will be closed soon without further activity. To keep the issue open, please respond to the comment to keep the discussion going.

**Comment by hickford** [comment]
The issue remains (contary to https://github.com/online-go/online-go.com/issues/176#issuecomment-495963674)

> Someone (hopefully you!) has requested a password reset for your online-go.com
account. To proceed, simply login with the following credentials:
> 
> Username: Guybrush Threepwood
> Password: 12345678

**Comment by BHydden** [comment]
Wow this is still happening??? Yeah agreed this is certainly not ideal.

**Comment by hickford** [comment]
I can still reproduce the issue, please reopen.
