### ISSUE TITLE
Score estimator is not turned off when navigating from AIReview component

### ISSUE THREAD

**Issue by mmartin** [online-go/online-go.com#1891]
**Describe the bug**
Score estimator mode is not turned off when navigating from AIReview component (either AIReviewChart or worst move list).

**To Reproduce**
1. Go to a finished game which has AI analysis;
2. Click `Estimate score`, wait for estimation to appear;
3. use AIReviewChart or worst moves buttons to navigate;
4. See that score estimator mode is still on.

**Screenshots**
After using AIReviewChart to navigate to beginning of the game:
![image](https://user-images.githubusercontent.com/236237/171016513-e395a449-740b-4d7b-aadb-f86b65bba465.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox, Chromium

**Additional context**
This was broken in #1779.

`stopEstimatingScore()` is called, but for some reason `estimating_score` is false.
https://github.com/online-go/online-go.com/blob/ce0ed666e73f19a93534dd948c569c40cd7f90ae/src/views/Game/Game.tsx#L648-L650

**Comment by anoek** [comment]
It's possible this was fixed with #2019, verification is needed

**Comment by Jlll1** [comment]
I tested this on latest devel branch, by navigating through the ai review move chart - the issue is still there.
After clicking Estimate Score:
![image](https://user-images.githubusercontent.com/71319302/196027786-247e59ab-d3ae-4898-87a4-5a1e2b42463b.png)
After clicking on the chart
![image](https://user-images.githubusercontent.com/71319302/196027867-4dc51c56-b97e-47d7-b5d0-b91b0792bb35.png)
![image](https://user-images.githubusercontent.com/71319302/196027847-c5b19d27-b126-4434-bcc9-d5c139798004.png)

**Comment by anoek** [comment]
This appears to have been fixed at some point
