### ISSUE TITLE
Split new users into Beginner/Intermediate/Advanced streams

### ISSUE THREAD

**Issue by dexonsmith** [online-go/online-go.com#2445]
This feature is to split new users into Beginner/Intermediate/Advanced streams. Background in the [forum proposal thread](https://forums.online-go.com/t/proposal-new-users-choose-beginner-intermediate-advanced-and-drop-ranked-game-restrictions/49983).

- New users choose between Beginner, Intermediate, or Advanced.
    - Beginner corresponds to 25k+–12k. The range won't be shown.
    - Intermediate corresponds to 16k–1k. The range is not immediately visible, but is shown if the user hovers or clicks on a `?` or something.
    - Advanced corresponds to 4k–9d+. The range is displayed on hover, like Intermediate.
- Depending on the choice, the player is assigned an initial rating of 743 (beginner), 1096 (intermediate), or 1764 (advanced).
    - This is instead of 1500, the old starting rating.
    - Deviation still 350.
    - The rating-to-rank conversion puts that at 22k, 12k, and 2k. (Not advertised to users up front.)
- Stop depressing the effective rank when the deviation is high. (I.e., remove code that made 1500+/-350 act as-if 12k.)

**Comment by GreenAsJade** [comment]
Done

**Comment by anoek** [comment]
Not quite? We still have the a/b experiment, which I think we can probably decide upon, but we should keep this open until that's settled I'd reckon?

**Comment by anoek** [comment]
I don't think we ever took out the A/B stuff for this, probably about time to wrap this up :)
