### ISSUE TITLE
Apple OS 26 breaks OGS channels in Safari

### ISSUE THREAD

**Issue by dexonsmith** [online-go/online-go.com#3239]
**Describe the bug**
In Apple's OS 26 updates, channel communication seems mostly broken. Experienced on macOS, iOS, and iPadOS.

Sometimes fiddling with WiFi settings (e.g., turning Airplane mode on, refreshing, turning it off, refreshing) will make channels work for a while. But not consistently. Also, desktop Macs don't have Airplane mode.

Examples of what's broken:
- There's a "red wifi" image above the user as if there's a bad network connection, even if the connection is great.
- Notification list empty.
- Games list has no game previews (although it does have the correct number of boards).
- After clicking on a game, the game does not load.
- The "Watch" button says there are no games being played.
    - You can observe this without logging in.

**To Reproduce**
1. Upgrade an Apple device to OS 26.
2. Log into online-go.com
3. Try to load a game or go to a list of games.

**Screenshots**

<img width="1167" height="1083" alt="Image" src="https://github.com/user-attachments/assets/ff4792ff-ea0c-472a-a7d0-2b37e919cd89" />
<img width="1178" height="276" alt="Image" src="https://github.com/user-attachments/assets/495096c6-c0e3-4537-b83a-038dcc865fa7" />
<img width="1171" height="175" alt="Image" src="https://github.com/user-attachments/assets/b94f731d-297f-4a0c-b67a-462384656cd3" />

**Desktop (please complete the following information):**
 - OS: macOS 26.0 ("Tahoe")
 - Browser: 26.0

**Smartphone (please complete the following information):**
 - Device: iPhone13Pro (also iPad Pro of some version)
 - OS: iOS26.0 (also iPadOS26.0)
 - Browser: Safari
 - Version: 26.0

**Additional context**
Reported on the forums here: https://forums.online-go.com/t/safari-connection-issue/58302

I'm happy to collect some logs on my desktop. Let me know what's useful.

**Comment by dexonsmith** [comment]
Note: sometimes it works, but I don't see a pattern. For example, just now I went back to the logged-out version of the Watch page (where I gathered that last screenshot) and the games were there / it worked correctly. Then I refreshed, and they disappeared.

**Comment by anoek** [comment]
Wow, it sounds like they are terminating any persistent websocket connections. We attempt to reconnect whenever that red connection indicator pops up so if that's staying, sounds like they're blocking it. Unless there is some magic Apple flag to make them stop breaking connections, our options might be limited other than file a bug report with Apple.

Any console log errors that look like they're related might provide some additional insight.

**Comment by dexonsmith** [comment]
<img width="1162" height="551" alt="Image" src="https://github.com/user-attachments/assets/cfac5ade-782d-4c0b-bd87-9551b5d5135e" />

This one eventually connected:

<img width="1162" height="202" alt="Image" src="https://github.com/user-attachments/assets/3f17a3da-731b-4980-a824-8534f1fc0972" />

Edit: a few minutes later, the next refresh is still failing to connect.

**Comment by dexonsmith** [comment]
> Wow, it sounds like they are terminating any persistent websocket connections.

This looks related: https://discussions.apple.com/thread/256142477?sortBy=rank

**Comment by anoek** [comment]
It's interesting there are some notes about GCP in there, we are on GCP but we by default go through CloudFlare and then GCP. 

Can you fiddle with this setting on the https://online-go.com/settings/general page and see if changing it makes any sort of difference?

<img width="667" height="83" alt="Image" src="https://github.com/user-attachments/assets/fcf0d003-2a65-449c-abca-8a25ed23ac53"  />

**Comment by dexonsmith** [comment]
I'll check that in a moment. In the meantime, I saw something about private relay here: https://github.com/brenner-tobias/addon-cloudflared/issues/904

I tried disabling private relay using "Reload and Show IP Address" based on these instructions: https://support.apple.com/en-us/102022

and it has worked in 3/3 attempts.

**Comment by anoek** [comment]
Very interesting, that sounds more promising

**Comment by dexonsmith** [comment]
> It's interesting there are some notes about GCP in there, we are on GCP but we by default go through CloudFlare and then GCP.
> 
> Can you fiddle with this setting on the https://online-go.com/settings/general page and see if changing it makes any sort of difference?
> 
> <img alt="Image" width="667" height="83" src="https://private-user-images.githubusercontent.com/168460/495227648-fcf0d003-2a65-449c-abca-8a25ed23ac53.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTkxNTY0MDcsIm5iZiI6MTc1OTE1NjEwNywicGF0aCI6Ii8xNjg0NjAvNDk1MjI3NjQ4LWZjZjBkMDAzLTJhNjUtNDQ5Yy1hYmNhLThhMjVlZDIzYWM1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDkyOVQxNDI4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWNiNjljMWM1YjE5NDRkMjBiOGFmY2Y0ZGY2ZWFmN2UzZGQxMTI5MDllODk1YTZmNjBiYzI0NDFiZmRhN2U1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WKt5FROBj2VXyL6jR4jRzVwUX08Nkel9iqsmnPGg_6o">

- Cloudflare: broken
- Public Internet: works!
- Google: works!

**Comment by anoek** [comment]
Geeze, ok first BT can't use cloudflare, now ios 26 can't use cloudflare, getting a little suspicious.

**Comment by dexonsmith** [comment]
Weird that Cloudflare doesn't work, given that they're one of Apple's partners for implementing iCloud Private Relay (according to a web search):
- https://www.idownloadblog.com/2022/03/03/icloud-private-relay-cloudflare-explanation/
- https://blog.cloudflare.com/icloud-private-relay/
(etc.)

Hopefully they're motivated to fix it since this seems kind of widespread...

**Comment by anoek** [comment]
I do consider it promising that it's not just a few sites that are affected, so there's definitely hope. At least we have a workaround now as well. I'll see about just routing all mac users through GCP by default to mitigate for the time being.

Thanks for doing testing through all of this!

**Comment by dexonsmith** [comment]
> I'll see about just routing all mac users through GCP by default to mitigate for the time being.
> 

Just to confirm, it affects iOS and iPadOS too. I was travelling the last few weeks and it's been really bad... just didn't get around to filing a bug till I got back (easier for me to do all the screen shots etc on a Mac). 

I suggest routing all Safari users (26.0 and higher) since private relay doesn't function in other browsers. (Or Safari, on *OS26)

**Comment by anoek** [comment]
👍 

And just to confirm, when you did your Google / Public test, were you using the private relay or did you have to turn that off too?

**Comment by dexonsmith** [comment]
> were you using the private relay

Yes I was.

> did you have to turn that off too?

No. Changing to Google / Public was sufficient.

**Comment by anoek** [comment]
I *think* this is resolved now, please re-open if that turns out to not be the case. Thanks again for working through it so quickly with me!

**Comment by dexonsmith** [comment]
Thanks for the quick fix! Confirmed it works consistently on my phone.

**Comment by dexonsmith** [comment]
And: Just now I returned "Websocket network to use" back to "Automatic" (the default) on my Mac and that works again. ("Cloudflare" still doesn't work, as expected.)
