### ISSUE TITLE
In chatroom, the users list can't toggle well

### ISSUE THREAD

**Issue by arnaudgo** [online-go/online-go.com#334]
### Summary

Applies to mobile version:

In the chat, the button to toggle the channels/rooms list works well but the one for users list does not.
If you click once on it, it shows up but no way for making hide again.

### Environment

 * Operating system: Android
 * Browser: Firefox
 * Browser Version: latest

### Steps To Reproduce:

Ask if needed

### Additional Information:

Ask if needed

Arnaud

**Comment by arnaudgo** [comment]
Hello,

And for those who didn't notice: on Chrome (my version is 59.0.3071.125) under Android, both actions work well.

Weird...

Arnaud

**Comment by anoek** [comment]
This appears to have been fixed at some point

**Comment by arnaudgo** [comment]
Hi @anoek , unfortunately, it is still not toggling but I can notice something has changed: now there's an overlap.
When I "click" on it with my finger ... the little window of the user appears and totally hides the little symbol.

See the enclosed screenshots.

![chatuserslist-1](https://user-images.githubusercontent.com/26174230/28586415-a02be8a8-716b-11e7-8346-6e16687c0295.png)
![chatuserslist-2](https://user-images.githubusercontent.com/26174230/28586416-a02c6f26-716b-11e7-8449-3d0b5163d53b.png)

Arnaud

**Comment by anoek** [comment]
I'm sorry I miss read, didn't catch it's on Firefox only
